name:                celanimate
version:             0.1.0.0
github:              "fujiy00/celanimate"
license:             BSD3
author:              "Yuuki Fujihara"
maintainer:          "mail@fujiy.me"
copyright:           "2019 Yuuki Fujihara"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fujiy00/celanimate#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- primitive
- mtl
- containers
- vector
- lens
- data-default
- JuicyPixels
- hip
- kdt
- union-find
- linear
- cubicbezier
- file-embed
- ghcjs-dom
- jsaddle
- jsaddle-dom
- reflex
- reflex-dom
- reflex-dom-core
- clay
# - hylogen
# - ombra

# default-extensions: OverloadedStrings

library:
  source-dirs: src

executables:
  celanimate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - celanimate

tests:
  celanimate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - celanimate
